---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: arm64

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: wdcurryii/drone-kubectl-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
