---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: arm64

steps:
- name: build docker image
  image: plugins/docker
  environment:
    KUBECTL_VERSION: "1.18.10"
  settings:
    repo: wdcurryii/drone-kubectl-arm64
    tags:
      - '1.18'
      - '1.18.10'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
