#!/usr/bin/env bash

KUBECTL_BIN=/usr/local/bin/kubectl

set -e

if [ -z ${PLUGIN_NAMESPACE} ]; then
  PLUGIN_NAMESPACE="default"
fi

if [ -z ${PLUGIN_KUBERNETES_USER} ]; then
  PLUGIN_KUBERNETES_USER="default"
fi

if [ ! -z ${PLUGIN_KUBERNETES_TOKEN} ]; then
  KUBERNETES_TOKEN=${PLUGIN_KUBERNETES_TOKEN}
fi

if [ ! -z ${PLUGIN_KUBERNETES_SERVER} ]; then
  KUBERNETES_SERVER=${PLUGIN_KUBERNETES_SERVER}
fi

if [ ! -z ${PLUGIN_KUBERNETES_CERT} ]; then
  KUBERNETES_CERT=${PLUGIN_KUBERNETES_CERT}
fi

${KUBECTL_BIN} config set-credentials default --token=${KUBERNETES_TOKEN}

if [ ! -z ${KUBERNETES_CERT} ]; then
  echo ${KUBERNETES_CERT} | base64 -d > ca.crt
  ${KUBECTL_BIN} config set-cluster default --server=${KUBERNETES_SERVER} --certificate-authority=ca.crt
else
  echo "WARNING: Using insecure connection to cluster"
  ${KUBECTL_BIN} config set-cluster default --server=${KUBERNETES_SERVER} --insecure-skip-tls-verify=true
fi

${KUBECTL_BIN} config set-context default --cluster=default --user=${PLUGIN_KUBERNETES_USER}
${KUBECTL_BIN} config use-context default
