#!/usr/bin/env bash

set -e

PATH="/opt/drone-kubectl-arm64/bin:$PATH"

INIT_FILE=/opt/drone-kubectl-arm64/initialized

if [ ! -f ${INIT_FILE} ]; then
    init-kubectl
    touch ${INIT_FILE}
fi

kubectl $@
